### PR TITLE
Version bump: www-servers/nginx-1.7.10

### PR DESCRIPTION
**Pull request by jbergstroem**
A slightly delayed version, mostly because ajp support broke in 1.7.9.
Updated modules:
 - cache_purge
 - auth_pam
 - modsecurity
 - ajp
 - mod_lua
 - fancyindex

Some homepages and version paths had to be updated. Most notably the ajp
module, where we're now running a specific git revision, awaiting an
upstream release.

This bump also fixes https://bugs.gentoo.org/show_bug.cgi?id=522994#c8

### CODE REVIEW

**Comment by Whissi** [comment]
Looks almost perfect:
```diff
--- nginx-1.7.10.ebuild.new	2015-02-28 13:38:52.509719143 +0100
+++ nginx-1.7.10.ebuild	2015-02-28 13:49:43.561801902 +0100
@@ -1,4 +1,4 @@
-# Copyright 1999-2014 Gentoo Foundation
+# Copyright 1999-2015 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Header: $
 
@@ -59,7 +59,7 @@
 HTTP_LUA_MODULE_URI="https://github.com/openresty/lua-nginx-module/archive/v${HTTP_LUA_MODULE_PV}.tar.gz"
 HTTP_LUA_MODULE_WD="${WORKDIR}/lua-nginx-module-${HTTP_LUA_MODULE_PV}"
 
-# http_auth_pam (https://github.com/stogh/ngx_http_auth_pam_module/, BSD-2 license)
+# http_auth_pam (http://web.iti.upv.es/~sto/nginx/, https://github.com/stogh/ngx_http_auth_pam_module, BSD-2 license)
 HTTP_AUTH_PAM_MODULE_PV="1.4"
 HTTP_AUTH_PAM_MODULE_P="ngx_http_auth_pam-${HTTP_AUTH_PAM_MODULE_PV}"
 HTTP_AUTH_PAM_MODULE_URI="https://github.com/stogh/ngx_http_auth_pam_module/archive/v${HTTP_AUTH_PAM_MODULE_PV}.tar.gz"
@@ -211,8 +211,8 @@
 CDEPEND="
 	pcre? ( >=dev-libs/libpcre-4.2 )
 	pcre-jit? ( >=dev-libs/libpcre-8.20[jit] )
-	ssl? ( dev-libs/openssl )
-	http-cache? ( userland_GNU? ( dev-libs/openssl ) )
+	ssl? ( dev-libs/openssl:= )
+	http-cache? ( userland_GNU? ( dev-libs/openssl:= ) )
 	nginx_modules_http_geoip? ( dev-libs/geoip )
 	nginx_modules_http_gunzip? ( sys-libs/zlib )
 	nginx_modules_http_gzip? ( sys-libs/zlib )
@@ -220,10 +220,10 @@
 	nginx_modules_http_image_filter? ( media-libs/gd[jpeg,png] )
 	nginx_modules_http_perl? ( >=dev-lang/perl-5.8 )
 	nginx_modules_http_rewrite? ( >=dev-libs/libpcre-4.2 )
-	nginx_modules_http_secure_link? ( userland_GNU? ( dev-libs/openssl ) )
-	nginx_modules_http_spdy? ( >=dev-libs/openssl-1.0.1c )
+	nginx_modules_http_secure_link? ( userland_GNU? ( dev-libs/openssl:= ) )
+	nginx_modules_http_spdy? ( >=dev-libs/openssl-1.0.1c:= )
 	nginx_modules_http_xslt? ( dev-libs/libxml2 dev-libs/libxslt )
-	nginx_modules_http_lua? ( !luajit? ( dev-lang/lua ) luajit? ( dev-lang/luajit ) )
+	nginx_modules_http_lua? ( !luajit? ( dev-lang/lua:= ) luajit? ( dev-lang/luajit:= ) )
 	nginx_modules_http_auth_pam? ( virtual/pam )
 	nginx_modules_http_metrics? ( dev-libs/yajl )
 	nginx_modules_http_dav_ext? ( dev-libs/expat )
@@ -514,7 +514,7 @@
 }
 
 src_install() {
-	emake DESTDIR="${D}" install
+	emake DESTDIR="${D%/}" install
 
 	cp "${FILESDIR}"/nginx.conf "${ED}"etc/nginx/nginx.conf || die
 
@@ -552,7 +552,7 @@
 
 	if use nginx_modules_http_perl; then
 		cd "${S}"/objs/src/http/modules/perl/
-		einstall DESTDIR="${D}" INSTALLDIRS=vendor
+		einstall DESTDIR="${D%/}" INSTALLDIRS=vendor
 		perl_delete_localpod
 	fi
 
@@ -663,7 +663,7 @@
 		ewarn "Check if this is correct for your setup before restarting nginx!"
 		ewarn "This is a one-time change and will not happen on subsequent updates."
 		ewarn "Furthermore nginx' temp directories got moved to ${NGINX_HOME_TMP}"
-		chmod -f o-rwx "${EPREFIX}"/var/log/nginx "${EPREFIX}/${NGINX_HOME_TMP}"/{,client,proxy,fastcgi,scgi,uwsgi}
+		chmod -f o-rwx "${EPREFIX}"/var/log/nginx "${EPREFIX}${NGINX_HOME_TMP}"/{,client,proxy,fastcgi,scgi,uwsgi}
 	fi
 
 	# If the nginx user can't change into or read the dir, display a warning.
```

**Comment by jbergstroem** [comment]
Thanks for the feedback. Will push a new version later today.

**Comment by jbergstroem** [comment]
Ping @Whissi -- PTAL.

**Comment by Whissi** [comment]
Now I am fine with the ebuild. Thank you, too.

PS: You maybe want to add https://github.com/mrueg/repoman-travis to your repository.

**Comment by piwats** [comment]
Will this ebuild land in the official gentoo portage repo?

**Comment by jbergstroem** [comment]
Yes, very shortly

**Pull request merged**
