### PR TITLE
Version bump: www-servers/nginx-1.7.10

### PR DESCRIPTION
**Pull request by Whissi**
- Bump to v1.7.9

- D, ED, EROOT and NGINX_HOME_TMP usage corrected
  (already proposed in https://bugs.gentoo.org/show_bug.cgi?id=522994#c8)

### CODE REVIEW

**Comment by jbergstroem** [comment]
Thanks for your contribution. Few things:
 - While bumping, also review the third party modules, some has newer versions
 - The ajp module unfortunately doesn't build, which is why I haven't bumped it yet. There's a patch floating, but I don't think its there yet. More info here: https://github.com/yaoweibin/nginx_ajp_module/issues/33

The ajp issue is the main reason I haven't bumped quite yet, but I'd be happy to accept your pull req as soon as it's merged. I usually enable all use-flags and third party modules (http and mail) when building nginx. I'll update the notes for contributing to add this.

**Comment by Whissi** [comment]
@jbergstroem I know that you are working on this (I am following your upstream bug reports) but please consider adding a mask for the non working 3rd party modules but don't hold back nginx.

For example, the ajp module is an edge use case, we are now >60 days behind nginx upstream just because of missing 3rd party modules.

**Comment by Whissi** [comment]
I rebased my PR and changed it for nginx-1.7.10.

I checked all the 3rd party modules like you told me.

Also, `NGINX_MODULES_HTTP="ajp cache_purge security" ebuild nginx-1.7.10.ebuild clean install` passed (you said ajp for example doesn't even build).

**Comment by jbergstroem** [comment]
ajp doesn't build. Not sure why you get it passing, but it's most likely to an error on your end. If you check the nginx source between 1.7.8 and 1.7.9, the abi has clearly changed -- see above link to bug. Here's additional output:
```
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c: In function 'ngx_http_ajp_store':
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c:467:30: warning: comparison between pointer and integer
     if (alcf->upstream.cache != NGX_CONF_UNSET_PTR
                              ^
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c:468:33: warning: comparison between pointer and integer
         && alcf->upstream.cache != NULL)
                                 ^
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c: In function 'ngx_http_ajp_cache':
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c:540:30: warning: comparison between pointer and integer
     if (alcf->upstream.cache != NGX_CONF_UNSET_PTR) {
                              ^
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c:545:30: warning: assignment makes integer from pointer without a cast
         alcf->upstream.cache = NULL;
                              ^
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c:553:26: warning: assignment makes integer from pointer without a cast
     alcf->upstream.cache = ngx_shared_memory_add(cf, &value[1], 0,
                          ^
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c:555:30: warning: comparison between pointer and integer
     if (alcf->upstream.cache == NULL) {
                              ^
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c: In function 'ngx_http_ajp_create_loc_conf':
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c:669:26: warning: assignment makes integer from pointer without a cast
     conf->upstream.cache = NGX_CONF_UNSET_PTR;
                          ^
In file included from src/core/ngx_core.h:76:0,
                 from /var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c:3:
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c: In function 'ngx_http_ajp_merge_loc_conf':
src/core/ngx_conf_file.h:252:14: warning: comparison between pointer and integer
     if (conf == NGX_CONF_UNSET_PTR) {                                        \
              ^
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c:867:5: note: in expansion of macro 'ngx_conf_merge_ptr_value'
     ngx_conf_merge_ptr_value(conf->upstream.cache,
     ^
src/core/ngx_conf_file.h:253:22: warning: comparison between pointer and integer
         conf = (prev == NGX_CONF_UNSET_PTR) ? default : prev;                \
                      ^
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c:867:5: note: in expansion of macro 'ngx_conf_merge_ptr_value'
     ngx_conf_merge_ptr_value(conf->upstream.cache,
     ^
src/core/ngx_conf_file.h:253:55: warning: pointer/integer type mismatch in conditional expression
         conf = (prev == NGX_CONF_UNSET_PTR) ? default : prev;                \
                                                       ^
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c:867:5: note: in expansion of macro 'ngx_conf_merge_ptr_value'
     ngx_conf_merge_ptr_value(conf->upstream.cache,
     ^
src/core/ngx_conf_file.h:253:14: warning: assignment makes integer from pointer without a cast
         conf = (prev == NGX_CONF_UNSET_PTR) ? default : prev;                \
              ^
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c:867:5: note: in expansion of macro 'ngx_conf_merge_ptr_value'
     ngx_conf_merge_ptr_value(conf->upstream.cache,
     ^
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c:870:53: error: invalid type argument of '->' (have 'int')
     if (conf->upstream.cache && conf->upstream.cache->data == NULL) {
                                                     ^
/var/tmp/portage/www-servers/nginx-1.7.10/work/nginx_ajp_module-0.3.0/ngx_http_ajp_module.c:873:18: warning: assignment makes pointer from integer without a cast
         shm_zone = conf->upstream.cache;
                  ^
objs/Makefile:2582: recipe for target 'objs/addon/nginx_ajp_module-0.3.0/ngx_http_ajp_module.o' failed
```

I'll wait one more week before disabling ajp until upstream responds. I know this situation is suboptimal, but we need to stand by our choice until next nginx stable forms (and our set of third party modules plays with it). Once that is done we'll do two active branches.

**Comment by Whissi** [comment]
Very strange, see my build log: https://bpaste.net/show/b6d184a10d21

I also created a location with `ajp_*` options and it is working (well, because I don't have a tomcat upstream, I'll get a `bad gateway` in the end, but it is not crashing or something else.

**Comment by jbergstroem** [comment]
Hm, at least one other guy in that issue seems to be able to reproduce. I build with all http and mail modules (as well as most use flags from time to time). It's pretty rare that modules conflict, but I won't rule it out. I'll do some tinkering.

**Comment by jbergstroem** [comment]
great news, this just landed: https://github.com/yaoweibin/nginx_ajp_module/commit/bf6cd93f2098b59260de8d494f0f4b1f11a84627

I'll push a new version shortly.

**Comment by jbergstroem** [comment]
@Whissi I'm closing this in favour of #19. Please review.

**Pull request closed without merging**
